kind = "mobile"
previewPath = "/"
title = "FarmEasy"
version = "1.0.0"
id = "artifacts/farmeasy"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 23031

[services.development]
run = "pnpm --filter @workspace/farmeasy run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/farmeasy", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/farmeasy", "run", "serve" ]

[services.env]
PORT = "23031"
BASE_PATH = "/"
