import type { MetricDef } from "./types";

/**
 * Shipments-tab metrics. `source`:
 * - shipments: Tier A — derived client-side from the GET /api/shipments list (M1).
 * - metrics: Tier B — GET /api/metrics (M2+).
 *
 * The shipments DataTable itself stays a page-level widget (not a metric).
 */
export const SHIPMENTS_METRICS: MetricDef[] = [
  // ── Sales / revenue ───────────────────────────────────────────────────
  { id: "sh.sold.total", tab: "shipments", label: "Total Yield Sold", category: "Sales / revenue", description: "SUM yield_sold_kg across shipments (excludes deleted).", unit: "kg", window: "all", render: "kpi", dataKey: "yieldSoldKg", source: "shipments", defaultSelected: true },
  { id: "sh.rev.total", tab: "shipments", label: "Total Revenue", category: "Sales / revenue", description: "SUM revenue_usd across shipments.", unit: "USD", window: "all", render: "kpi", dataKey: "revenueUsd", source: "shipments", defaultSelected: true },
  { id: "sh.rev.avgPerShip", tab: "shipments", label: "Avg Revenue / Shipment", category: "Sales / revenue", description: "SUM revenue_usd / COUNT shipments.", unit: "USD", window: "all", render: "kpi", dataKey: "revenueUsd", source: "shipments", defaultSelected: false },
  { id: "sh.sold.avgPerShip", tab: "shipments", label: "Avg Yield / Shipment", category: "Sales / revenue", description: "SUM yield_sold_kg / COUNT shipments.", unit: "kg", window: "all", render: "kpi", dataKey: "yieldSoldKg", source: "shipments", defaultSelected: false },
  { id: "sh.rev.byMonth", tab: "shipments", label: "Revenue by Month", category: "Sales / revenue", description: "SUM revenue_usd per month (date_trunc).", unit: "USD", window: "all", render: "bar", dataKey: "sh.rev.byMonth", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "shipments", measure: "revenue_usd", dateCol: "shipping_date", bucket: "month", where: "deleted_at IS NULL" } },
  { id: "sh.rev.byClient", tab: "shipments", label: "Revenue by Client", category: "Sales / revenue", description: "SUM revenue_usd grouped by client.", unit: "USD", window: "all", render: "hbar", dataKey: "sh.rev.byClient", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "shipments", measure: "revenue_usd", dim: "client", where: "deleted_at IS NULL" } },
  { id: "sh.sold.byMonth", tab: "shipments", label: "Yield Sold by Month", category: "Sales / revenue", description: "SUM yield_sold_kg per month.", unit: "kg", window: "all", render: "bar", dataKey: "sh.sold.byMonth", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "shipments", measure: "yield_sold_kg", dateCol: "shipping_date", bucket: "month", where: "deleted_at IS NULL" } },
  { id: "sh.sold.byClient", tab: "shipments", label: "Yield Sold by Client", category: "Sales / revenue", description: "SUM yield_sold_kg grouped by client.", unit: "kg", window: "all", render: "hbar", dataKey: "sh.sold.byClient", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "shipments", measure: "yield_sold_kg", dim: "client", where: "deleted_at IS NULL" } },
  { id: "sh.revVsSold.scatter", tab: "shipments", label: "Revenue vs Yield Sold", category: "Sales / revenue", description: "revenue_usd vs yield_sold_kg per shipment.", unit: "", window: "all", render: "scatter", dataKey: "sh.revVsSold.scatter", source: "metrics", defaultSelected: false, template: "table", templateParams: { table: "shipments", cols: "revenue_usd,yield_sold_kg", where: "deleted_at IS NULL" }, topN: 500 },
  { id: "sh.rev.thisMonth", tab: "shipments", label: "Revenue This Month", category: "Sales / revenue", description: "SUM revenue_usd where shipping_date >= monthStart.", unit: "USD", window: "30d", render: "kpi", dataKey: "revenueUsd", source: "shipments", defaultSelected: false },
  { id: "sh.rev.growth", tab: "shipments", label: "Revenue Growth", category: "Sales / revenue", description: "Last 30d revenue vs the 30d before that.", unit: "%", window: "all", render: "kpi", dataKey: "sh.rev.growth", source: "metrics", defaultSelected: false, template: "custom", templateParams: { key: "sh.rev.growth" }, requires: ["revenue"] },
  { id: "sh.rev.topClients", tab: "shipments", label: "Top Clients by Revenue", category: "Sales / revenue", description: "Top 5 clients by SUM revenue_usd.", unit: "USD", window: "all", render: "hbar", dataKey: "sh.rev.topClients", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "shipments", measure: "revenue_usd", dim: "client", order: "desc", limit: 5 } },
  { id: "sh.clients.count", tab: "shipments", label: "Distinct Clients", category: "Sales / revenue", description: "COUNT DISTINCT client.", unit: "count", window: "all", render: "kpi", dataKey: "client", source: "shipments", defaultSelected: false },
  { id: "sh.aov", tab: "shipments", label: "Avg Order Value", category: "Sales / revenue", description: "SUM revenue_usd / COUNT shipments.", unit: "USD", window: "all", render: "kpi", dataKey: "revenueUsd", source: "shipments", defaultSelected: false },

  // ── Economics / decision (Rev 2) ──────────────────────────────────────
  { id: "sh.econ.pricePerKg", tab: "shipments", label: "Price per kg", category: "Economics / decision", description: "SUM revenue_usd / SUM yield_sold_kg per period.", unit: "USD/kg", window: "range", render: "kpi", dataKey: "sh.econ.pricePerKg", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { numTable: "shipments", numMeasure: "revenue_usd", denTable: "shipments", denMeasure: "yield_sold_kg", numWhere: "deleted_at IS NULL", denWhere: "deleted_at IS NULL" }, requires: ["revenue"] },
  { id: "sh.econ.pricePerKgByClient", tab: "shipments", label: "$/kg by Client", category: "Economics / decision", description: "Price per kg grouped by client — shows who underpays.", unit: "USD/kg", window: "range", render: "hbar", dataKey: "sh.econ.pricePerKgByClient", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { numTable: "shipments", numMeasure: "revenue_usd", denMeasure: "yield_sold_kg", dim: "client" }, requires: ["revenue"] },
  { id: "sh.econ.marginByCrop", tab: "shipments", label: "Contribution Margin / Crop", category: "Economics / decision", description: "SUM revenue − SUM consumed cost per crop. Blocked until stock_movements carries unit cost (schema change).", unit: "USD", window: "range", render: "bar", dataKey: "sh.econ.marginByCrop", source: "metrics", defaultSelected: false, requires: ["revenue", "cost"] },
  { id: "sh.econ.wasteRate", tab: "shipments", label: "Waste / Shrink %", category: "Economics / decision", description: "(SUM harvested_qty − SUM yield_sold_kg) / SUM harvested_qty for completed cycles (linked shipments only).", unit: "%", window: "all", render: "kpi", dataKey: "sh.econ.wasteRate", source: "metrics", defaultSelected: false, template: "custom", templateParams: { key: "sh.econ.wasteRate" } },

  // ── Status / operations ───────────────────────────────────────────────
  { id: "sh.status.complete", tab: "shipments", label: "Completed Shipments", category: "Status / operations", description: "Count of shipments with status=complete.", unit: "count", window: "all", render: "kpi", dataKey: "status", source: "shipments", defaultSelected: true },
  { id: "sh.status.pending", tab: "shipments", label: "Pending Shipments", category: "Status / operations", description: "Count of shipments with status=pending.", unit: "count", window: "all", render: "kpi", dataKey: "status", source: "shipments", defaultSelected: true },
  { id: "sh.status.inProgress", tab: "shipments", label: "In-Progress Shipments", category: "Status / operations", description: "Count of shipments with status=in_progress.", unit: "count", window: "all", render: "kpi", dataKey: "status", source: "shipments", defaultSelected: false },
  { id: "sh.byStatus", tab: "shipments", label: "Shipments by Status", category: "Status / operations", description: "Count grouped by status.", unit: "count", window: "all", render: "donut", dataKey: "status", source: "shipments", defaultSelected: false },
  { id: "sh.overTime", tab: "shipments", label: "Shipments over Time", category: "Status / operations", description: "Count per week (date_trunc).", unit: "count", window: "all", render: "line", dataKey: "sh.overTime", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "shipments", measure: "*", dateCol: "shipping_date", bucket: "week", where: "deleted_at IS NULL" } },
  { id: "sh.cycleTime", tab: "shipments", label: "Ship Cycle Time", category: "Status / operations", description: "AVG(shipping_date − cycle.closed_at) for linked cycles.", unit: "days", window: "all", render: "kpi", dataKey: "sh.cycleTime", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "shipments", measure: "extract(epoch from (shipping_date - c.closed_at))/86400", agg: "avg", join: "cycles c ON c.id = shipments.cycle_id", where: "shipments.cycle_id IS NOT NULL" } },

  // ── Traceability ──────────────────────────────────────────────────────
  { id: "sh.linkedCycles", tab: "shipments", label: "Shipments Linked to Cycles", category: "Traceability", description: "Count where cycle_id IS NOT NULL. (Tier B — cycle_id is not in the shipments list payload.)", unit: "count", window: "all", render: "kpi", dataKey: "sh.linkedCycles", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "shipments", measure: "*", where: "cycle_id IS NOT NULL AND deleted_at IS NULL" } },
  { id: "sh.unlinked", tab: "shipments", label: "Unlinked Shipments", category: "Traceability", description: "Shipments with cycle_id IS NULL. (Tier B.)", unit: "count", window: "all", render: "kpi", dataKey: "sh.unlinked", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "shipments", measure: "*", where: "cycle_id IS NULL AND deleted_at IS NULL" } },
  { id: "sh.soldVsHarvested", tab: "shipments", label: "Sold vs Harvested", category: "Traceability", description: "SUM yield_sold_kg vs SUM harvested_qty over period (reconciliation, linked cycles only).", unit: "kg", window: "all", render: "kpi", dataKey: "sh.soldVsHarvested", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { numTable: "shipments", numMeasure: "yield_sold_kg", denTable: "cycles", denMeasure: "harvested_qty", numWhere: "deleted_at IS NULL AND cycle_id IS NOT NULL", denWhere: "status='completed' AND deleted_at IS NULL" } },
  { id: "sh.trace.oneUpDown", tab: "shipments", label: "Client ↔ Cycle ↔ Lot Trace", category: "Traceability", description: "One-up/one-down: shipments → cycles → cycle_seed_lots → seed_lots.", unit: "", window: "all", render: "table", dataKey: "sh.trace.oneUpDown", source: "metrics", defaultSelected: false, topN: 50, resourceLink: "/shipments" },
  { id: "sh.recall.exposure", tab: "shipments", label: "Recall Exposure by Lot", category: "Traceability", description: "Clients exposed per seed lot (cycle_seed_lots → cycles → shipments.client).", unit: "", window: "all", render: "table", dataKey: "sh.recall.exposure", source: "metrics", defaultSelected: false, topN: 50, resourceLink: "/shipments" },
];