import type { MetricDef } from "./types";

/**
 * Inventory-tab metrics. `source`:
 * - inventory/dashboard: Tier A — derived from GET /api/inventory + dashboard
 *   payloads (M1).
 * - metrics: Tier B — GET /api/metrics (M2+), mostly the stock_movements ledger.
 *
 * The inventory DataTable stays a page-level widget (not a metric).
 */
export const INVENTORY_METRICS: MetricDef[] = [
  // ── Stock levels ──────────────────────────────────────────────────────
  { id: "inv.items.total", tab: "inventory", label: "Total Supply Items", category: "Stock levels", description: "Count of inventory_items (not deleted).", unit: "count", window: "all", render: "kpi", dataKey: "items", source: "inventory", defaultSelected: true },
  { id: "inv.lowStock.count", tab: "inventory", label: "Low-Stock Alerts", category: "Stock levels", description: "Items where current_qty/max_qty < 0.2.", unit: "count", window: "all", render: "kpi", dataKey: "items", source: "inventory", defaultSelected: true },
  { id: "inv.lowStock.list", tab: "inventory", label: "Low-Stock Items", category: "Stock levels", description: "List of items below the low-stock threshold.", unit: "", window: "all", render: "list", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.byCategory.count", tab: "inventory", label: "Items by Category", category: "Stock levels", description: "Count of items grouped by category.", unit: "count", window: "all", render: "donut", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.byCategory.qty", tab: "inventory", label: "Qty by Category", category: "Stock levels", description: "SUM current_qty per category.", unit: "count", window: "all", render: "bar", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.byItem.qty", tab: "inventory", label: "Qty by Item", category: "Stock levels", description: "current_qty per item.", unit: "count", window: "all", render: "hbar", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.fillRate", tab: "inventory", label: "Stock Fill Rate", category: "Stock levels", description: "SUM current_qty / SUM max_qty.", unit: "%", window: "all", render: "gauge", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.outOfStock", tab: "inventory", label: "Out-of-Stock Items", category: "Stock levels", description: "Items with current_qty = 0.", unit: "count", window: "all", render: "kpi", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.itemAge", tab: "inventory", label: "Stock Age by Arrival", category: "Stock levels", description: "Age since arrival_date.", unit: "days", window: "all", render: "list", dataKey: "items", source: "inventory", defaultSelected: false },
  { id: "inv.newestArrivals", tab: "inventory", label: "Newest Arrivals", category: "Stock levels", description: "Items ordered by arrival_date desc.", unit: "", window: "all", render: "list", dataKey: "items", source: "inventory", defaultSelected: false },

  // ── Stock movements (ledger) ──────────────────────────────────────────
  { id: "inv.mov.overTime", tab: "inventory", label: "Movements over Time", category: "Stock movements", description: "Count of stock_movements per day/week.", unit: "count", window: "range", render: "line", dataKey: "inv.mov.overTime", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "stock_movements", measure: "*", dateCol: "created_at", bucket: "week" } },
  { id: "inv.mov.netByMonth", tab: "inventory", label: "Net Stock Change / Month", category: "Stock movements", description: "SUM delta per month.", unit: "count", window: "all", render: "bar", dataKey: "inv.mov.netByMonth", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "stock_movements", measure: "delta", dateCol: "created_at", bucket: "month" } },
  { id: "inv.mov.byReason", tab: "inventory", label: "Movements by Reason", category: "Stock movements", description: "Count grouped by reason (purchase/consume/adjust).", unit: "count", window: "all", render: "donut", dataKey: "inv.mov.byReason", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "stock_movements", measure: "*", dim: "reason" } },
  { id: "inv.mov.consumeByCycle", tab: "inventory", label: "Consumption per Cycle", category: "Stock movements", description: "SUM delta where reason=consume, grouped by cycle_id.", unit: "count", window: "all", render: "bar", dataKey: "inv.mov.consumeByCycle", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "stock_movements", measure: "delta", dim: "cycle_id", where: "reason='consume'" } },
  { id: "inv.mov.topConsumed", tab: "inventory", label: "Top Consumed Items", category: "Stock movements", description: "SUM |delta| where reason=consume per item.", unit: "count", window: "all", render: "hbar", dataKey: "inv.mov.topConsumed", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "stock_movements", measure: "abs(delta)", dim: "inventory_item_id", where: "reason='consume'", order: "desc", limit: 10 } },
  { id: "inv.mov.purchases", tab: "inventory", label: "Restocks by Month", category: "Stock movements", description: "SUM delta where reason=purchase per month.", unit: "count", window: "all", render: "bar", dataKey: "inv.mov.purchases", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "stock_movements", measure: "delta", dateCol: "created_at", bucket: "month", where: "reason='purchase'" } },
  { id: "inv.mov.adjustments", tab: "inventory", label: "Adjustments", category: "Stock movements", description: "Count where reason=adjust.", unit: "count", window: "all", render: "kpi", dataKey: "inv.mov.adjustments", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "stock_movements", measure: "*", where: "reason='adjust'" } },
  { id: "inv.mov.turnover", tab: "inventory", label: "Inventory Turnover (30d)", category: "Stock movements", description: "Consumed qty (last 30d) / avg current stock.", unit: "", window: "all", render: "kpi", dataKey: "inv.mov.turnover", source: "metrics", defaultSelected: false, template: "custom", templateParams: { key: "inv.mov.turnover" } },
  { id: "inv.mov.daysRemaining", tab: "inventory", label: "Days of Stock Remaining", category: "Stock movements", description: "current_qty / avg daily consume rate (last 30d).", unit: "days", window: "all", render: "kpi", dataKey: "inv.mov.daysRemaining", source: "metrics", defaultSelected: false, template: "custom", templateParams: { key: "inv.mov.daysRemaining" } },
  { id: "inv.mov.cogsByCycle", tab: "inventory", label: "Consumption per Cycle (qty)", category: "Stock movements", description: "SUM delta where reason=consume grouped by cycle_id.", unit: "count", window: "all", render: "bar", dataKey: "inv.mov.cogsByCycle", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "stock_movements", measure: "delta", dim: "cycle_id", where: "reason='consume'" } },

  // ── Seed lots / crops (inventory-related) ─────────────────────────────
  { id: "inv.seedlots.active", tab: "inventory", label: "Active Seed Lots", category: "Seed lots / crops", description: "Seed lots currently in rotation.", unit: "count", window: "all", render: "kpi", dataKey: "activeSeedLots", source: "dashboard", defaultSelected: true },
  { id: "inv.seedlots.details", tab: "inventory", label: "Active Seed Lot Details", category: "Seed lots / crops", description: "Detail table of active seed lots (seedName, qrCode).", unit: "", window: "all", render: "table", dataKey: "activeSeedLotDetails", source: "dashboard", defaultSelected: false },
  { id: "inv.crops.activeTypes", tab: "inventory", label: "Active Crop Types", category: "Seed lots / crops", description: "Distinct crop_id in running cycles (rule 7).", unit: "count", window: "all", render: "kpi", dataKey: "activeCropTypes", source: "dashboard", defaultSelected: true },
  { id: "inv.seedlots.bySupplier", tab: "inventory", label: "Seed Lots by Supplier", category: "Seed lots / crops", description: "Count grouped by supplier.", unit: "count", window: "all", render: "bar", dataKey: "inv.seedlots.bySupplier", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "seed_lots", measure: "*", dim: "supplier" } },
  { id: "inv.seedlots.currentVsRetired", tab: "inventory", label: "Currently Grown vs Retired", category: "Seed lots / crops", description: "Count by currently_grown (bool).", unit: "count", window: "all", render: "donut", dataKey: "inv.seedlots.currentVsRetired", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "seed_lots", measure: "*", dim: "currently_grown" } },
];