import type { MetricDef } from "./types";

/**
 * Overview-tab metrics. `source`:
 * - dashboard/alerts: Tier A — derived from the GET /api/dashboard +
 *   useListAlerts payloads (M1). Visible in the M1 picker.
 * - metrics: Tier B — served by GET /api/metrics (M2+). Hidden from the M1
 *   picker (shown once the endpoint ships).
 *
 * Defaults reproduce today's Overview widgets exactly (incl. composite shims
 * `ov.combined.*`, `ov.cap.utilizationChart`, `ov.cycles.actionRequiredList`
 * which decompose into per-metric Tier-B cards in M3).
 */
export const OVERVIEW_METRICS: MetricDef[] = [
  // ── Yield / production ────────────────────────────────────────────────
  { id: "ov.yield.week", tab: "overview", label: "Total Yield (Week)", category: "Yield / production", description: "Sum of harvested_qty for cycles closed this week (facility-local Monday-start).", unit: "kg", window: "7d", render: "kpi", dataKey: "totalYieldThisWeek", source: "dashboard", defaultSelected: true, testId: "text-yield-week" },
  { id: "ov.yield.month", tab: "overview", label: "Total Yield (Month)", category: "Yield / production", description: "Sum of harvested_qty for cycles closed this month.", unit: "kg", window: "30d", render: "kpi", dataKey: "totalYieldThisMonth", source: "dashboard", defaultSelected: false },
  { id: "ov.yield.alltime", tab: "overview", label: "Total Yield (All-time)", category: "Yield / production", description: "Sum of harvested_qty for completed cycles (excludes deleted).", unit: "kg", window: "all", render: "kpi", dataKey: "ov.yield.alltime", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "cycles", measure: "harvested_qty", where: "status='completed' AND deleted_at IS NULL" } },
  { id: "ov.yield.byDay", tab: "overview", label: "Yield (last 7d)", category: "Yield / production", description: "Daily harvested_qty, last 7 days.", unit: "kg", window: "7d", render: "area", dataKey: "yieldByDay", source: "dashboard", defaultSelected: false },
  { id: "ov.yield.byWeek", tab: "overview", label: "Yield by Week", category: "Yield / production", description: "Weekly harvested_qty, last 4 weeks.", unit: "kg", window: "30d", render: "area", dataKey: "yieldByWeek", source: "dashboard", defaultSelected: true },
  { id: "ov.yield.byMonth", tab: "overview", label: "Yield by Month", category: "Yield / production", description: "Monthly harvested_qty (date_trunc month).", unit: "kg", window: "all", render: "bar", dataKey: "ov.yield.byMonth", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "cycles", measure: "harvested_qty", dateCol: "closed_at", bucket: "month", where: "status='completed' AND deleted_at IS NULL" } },
  { id: "ov.yield.byCrop", tab: "overview", label: "Yield by Crop", category: "Yield / production", description: "Harvested_qty grouped by crop (growth_profiles.crop_id; unlinked bucketed separately).", unit: "kg", window: "all", render: "hbar", dataKey: "ov.yield.byCrop", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "harvested_qty", dim: "crop_id", where: "deleted_at IS NULL" } },
  { id: "ov.yield.avgPerCycle", tab: "overview", label: "Avg Yield / Cycle", category: "Yield / production", description: "SUM harvested_qty / COUNT completed cycles.", unit: "kg", window: "all", render: "kpi", dataKey: "ov.yield.avgPerCycle", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { numTable: "cycles", numMeasure: "harvested_qty", denTable: "cycles", denMeasure: "*", denWhere: "status='completed' AND deleted_at IS NULL", numWhere: "status='completed' AND deleted_at IS NULL" } },
  { id: "ov.yield.avgPerTray", tab: "overview", label: "Avg Yield / Tray", category: "Yield / production", description: "SUM harvested_qty / SUM(full_trays + half_trays*0.5).", unit: "kg", window: "all", render: "kpi", dataKey: "ov.yield.avgPerTray", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { numTable: "cycles", numMeasure: "harvested_qty", denTable: "cycles", denMeasure: "full_trays+half_trays*0.5", numWhere: "deleted_at IS NULL", denWhere: "deleted_at IS NULL" } },
  { id: "ov.yield.expectedVsActual", tab: "overview", label: "Expected vs Actual Yield", category: "Yield / production", description: "growth_profiles.expected_yield_per_tray_kg * trays vs harvested_qty per cycle.", unit: "kg", window: "all", render: "bar", dataKey: "ov.yield.expectedVsActual", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "harvested_qty", dim: "crop_id" } },
  { id: "ov.yield.forecast", tab: "overview", label: "Upcoming Harvest (est)", category: "Yield / production", description: "SUM expected_yield_per_tray_kg * trays for non-completed cycles.", unit: "kg", window: "all", render: "kpi", dataKey: "ov.yield.forecast", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "cycles", measure: "expected_yield_per_tray_kg*(full_trays+half_trays*0.5)", where: "status<>'completed' AND deleted_at IS NULL" } },
  { id: "ov.yield.byChannel", tab: "overview", label: "Yield by Channel", category: "Yield / production", description: "Harvested_qty grouped by channel via cycles.tray_id.", unit: "kg", window: "all", render: "bar", dataKey: "ov.yield.byChannel", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "harvested_qty", dim: "channel_id" } },

  // ── Cycles / activity ─────────────────────────────────────────────────
  { id: "ov.cycles.active", tab: "overview", label: "Active Cycles", category: "Cycles / activity", description: "Count of cycles not in completed status.", unit: "count", window: "all", render: "kpi", dataKey: "totalRunningCycles", source: "dashboard", defaultSelected: true, testId: "text-active-cycles", panel: "cycles" },
  { id: "ov.cycles.byStatus", tab: "overview", label: "Cycles by Status", category: "Cycles / activity", description: "Count of cycles per status (germination/fertigation/harvest/completed).", unit: "count", window: "all", render: "donut", dataKey: "ov.cycles.byStatus", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "*", dim: "status", where: "deleted_at IS NULL" } },
  { id: "ov.cycles.actionNeeded", tab: "overview", label: "Cycles Needing Action", category: "Cycles / activity", description: "Cycles with overdue stage transitions (daysOverdue > 0).", unit: "count", window: "all", render: "kpi", dataKey: "actionRequired", source: "dashboard", defaultSelected: true, panel: "action-required" },
  { id: "ov.cycles.seededByDay", tab: "overview", label: "Seeding Weight by Day", category: "Cycles / activity", description: "Daily seed_weight_tray*(full+half*0.5), last 7 days.", unit: "g", window: "7d", render: "bar", dataKey: "seedingByDay", source: "dashboard", defaultSelected: false },
  { id: "ov.cycles.seededByWeek", tab: "overview", label: "Seeding Weight by Week", category: "Cycles / activity", description: "Weekly seeding weight, last 4 weeks.", unit: "g", window: "30d", render: "bar", dataKey: "seedingByWeek", source: "dashboard", defaultSelected: false },
  { id: "ov.cycles.avgDuration", tab: "overview", label: "Avg Cycle Duration", category: "Cycles / activity", description: "AVG(closed_at - seeding_date) for completed cycles.", unit: "days", window: "all", render: "kpi", dataKey: "ov.cycles.avgDuration", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "cycles", measure: "extract(epoch from (closed_at - seeding_date))/86400", agg: "avg", where: "status='completed' AND deleted_at IS NULL" } },
  { id: "ov.cycles.durationByCrop", tab: "overview", label: "Duration by Crop", category: "Cycles / activity", description: "AVG cycle duration grouped by crop_id (rule 7).", unit: "days", window: "all", render: "bar", dataKey: "ov.cycles.durationByCrop", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "extract(epoch from (closed_at - seeding_date))/86400", agg: "avg", dim: "crop_id" } },
  { id: "ov.cycles.overdue", tab: "overview", label: "Overdue Cycles", category: "Cycles / activity", description: "Count of cycles with daysOverdue > 0.", unit: "count", window: "all", render: "kpi", dataKey: "actionRequired", source: "dashboard", defaultSelected: false },
  { id: "ov.cycles.throughput", tab: "overview", label: "Completed Cycles / Week", category: "Cycles / activity", description: "Count of completed cycles per week.", unit: "count", window: "all", render: "line", dataKey: "ov.cycles.throughput", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "cycles", measure: "*", dateCol: "closed_at", bucket: "week", where: "status='completed' AND deleted_at IS NULL" } },
  { id: "ov.cycles.completionRate", tab: "overview", label: "Completion Rate (90d cohort)", category: "Cycles / activity", description: "Completed / cycles seeded in last 90d whose profile duration has elapsed (rule 6 same window+cohort).", unit: "%", window: "90d", render: "kpi", dataKey: "ov.cycles.completionRate", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { cohort: "90d" } },

  // ── Capacity / trays ──────────────────────────────────────────────────
  { id: "ov.cap.utilization", tab: "overview", label: "Channel Utilization", category: "Capacity / trays", description: "Running trays / total channels.", unit: "%", window: "all", render: "kpi", dataKey: "channelUtilization", source: "dashboard", defaultSelected: true, testId: "text-channel-util" },
  { id: "ov.cap.utilizationChart", tab: "overview", label: "Channel Utilization", category: "Capacity / trays", description: "Running vs idle channels, progress bar.", unit: "%", window: "all", render: "progress", dataKey: "channelUtilization", source: "dashboard", defaultSelected: true },
  { id: "ov.cap.utilByRoom", tab: "overview", label: "Utilization by Room", category: "Capacity / trays", description: "Per-room running trays / capacity.", unit: "%", window: "all", render: "bar", dataKey: "ov.cap.utilByRoom", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "*", dim: "room_id" } },
  { id: "ov.cap.rackOccupancy", tab: "overview", label: "Rack Occupancy", category: "Capacity / trays", description: "Trays occupied / capacity per rack.", unit: "%", window: "all", render: "heatmap", dataKey: "ov.cap.rackOccupancy", source: "metrics", defaultSelected: false },
  { id: "ov.cap.trayMix", tab: "overview", label: "Full vs Half Trays", category: "Capacity / trays", description: "SUM full_trays vs half_trays (running cycles).", unit: "count", window: "all", render: "stacked", dataKey: "ov.cap.trayMix", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "full_trays,half_trays", dim: "status" } },
  { id: "ov.cap.activeTrays", tab: "overview", label: "Active Trays", category: "Capacity / trays", description: "SUM(full + half*0.5) for running cycles.", unit: "count", window: "all", render: "kpi", dataKey: "ov.cap.activeTrays", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "cycles", measure: "full_trays+half_trays*0.5", where: "status<>'completed' AND deleted_at IS NULL" } },

  // ── Bad trays / loss ──────────────────────────────────────────────────
  { id: "ov.bad.count7d", tab: "overview", label: "Bad Trays", category: "Bad trays / loss", description: "Bad trays this week (bad_tray_entries after cutover, manual_checks legacy before — rule 4).", unit: "count", window: "7d", render: "kpi", dataKey: "totalBadTrays", source: "dashboard", defaultSelected: true, testId: "text-bad-trays", panel: "bad-trays" },
  { id: "ov.bad.weightByDay", tab: "overview", label: "Bad-Tray Weight by Day", category: "Bad trays / loss", description: "Daily bad-tray seed-weight loss, last 7 days.", unit: "g", window: "7d", render: "area", dataKey: "badTrayByDay", source: "dashboard", defaultSelected: false },
  { id: "ov.bad.weightByWeek", tab: "overview", label: "Bad-Tray Weight by Week", category: "Bad trays / loss", description: "Weekly bad-tray seed-weight loss.", unit: "g", window: "30d", render: "area", dataKey: "badTrayByWeek", source: "dashboard", defaultSelected: false },
  { id: "ov.bad.lossEstimate", tab: "overview", label: "Loss Estimate", category: "Bad trays / loss", description: "SUM bad_tray_entries.loss_estimate (USD — verify unit before first render).", unit: "USD", window: "all", render: "kpi", dataKey: "ov.bad.lossEstimate", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "bad_tray_entries", measure: "loss_estimate", where: "created_at >= :cutover" } },
  { id: "ov.bad.byIssue", tab: "overview", label: "Bad Trays by Issue", category: "Bad trays / loss", description: "Count of bad trays grouped by issue (rule 4 cutover).", unit: "count", window: "all", render: "bar", dataKey: "ov.bad.byIssue", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "bad_tray_entries", measure: "*", dim: "issue" } },
  { id: "ov.bad.bySeverity", tab: "overview", label: "Bad Trays by Severity", category: "Bad trays / loss", description: "Count by severity (low/medium/high).", unit: "count", window: "all", render: "donut", dataKey: "ov.bad.bySeverity", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "bad_tray_entries", measure: "*", dim: "severity" } },
  { id: "ov.bad.byCrop", tab: "overview", label: "Bad Trays by Crop", category: "Bad trays / loss", description: "Count grouped by crop_id (rule 7).", unit: "count", window: "all", render: "bar", dataKey: "ov.bad.byCrop", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "bad_tray_entries", measure: "*", dim: "crop_id" } },
  { id: "ov.bad.rate", tab: "overview", label: "Bad-Tray Rate (30d)", category: "Bad trays / loss", description: "Bad trays last 30d / trays seeded last 30d (rule 6 same window).", unit: "%", window: "30d", render: "kpi", dataKey: "ov.bad.rate", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { window: "30d" } },
  { id: "ov.bad.byChannel", tab: "overview", label: "Bad Trays by Channel", category: "Bad trays / loss", description: "Count by channel via tray_id.", unit: "count", window: "all", render: "bar", dataKey: "ov.bad.byChannel", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "bad_tray_entries", measure: "*", dim: "channel_id" } },

  // ── Sensors / environment ─────────────────────────────────────────────
  { id: "ov.sensor.onlineRatio", tab: "overview", label: "Sensors Online", category: "Sensors / environment", description: "Sensors with a recent reading / total (rule 5 staleness).", unit: "%", window: "all", render: "gauge", dataKey: "sensorStatus", source: "dashboard", defaultSelected: false },
  { id: "ov.sensor.currentTemp", tab: "overview", label: "Current Temp", category: "Sensors / environment", description: "Latest temp reading + read_at (rule 5).", unit: "count", render: "kpi", dataKey: "sensorStatus", source: "dashboard", defaultSelected: false },
  { id: "ov.sensor.currentPh", tab: "overview", label: "Current pH", category: "Sensors / environment", description: "Latest pH reading + read_at (rule 5).", unit: "count", render: "kpi", dataKey: "sensorStatus", source: "dashboard", defaultSelected: false },
  { id: "ov.sensor.currentHumidity", tab: "overview", label: "Current Humidity", category: "Sensors / environment", description: "Latest humidity reading + read_at (rule 5).", unit: "%", render: "kpi", dataKey: "sensorStatus", source: "dashboard", defaultSelected: false },
  { id: "ov.sensor.currentWater", tab: "overview", label: "Current Water Level", category: "Sensors / environment", description: "Latest water level + read_at (rule 5).", unit: "%", render: "kpi", dataKey: "sensorStatus", source: "dashboard", defaultSelected: false },
  { id: "ov.sensor.tempTrend", tab: "overview", label: "Temp Trend", category: "Sensors / environment", description: "Temp readings over time (sensor_readings, type=temp).", unit: "count", window: "range", render: "line", dataKey: "ov.sensor.tempTrend", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "sensor_readings", measure: "value", dateCol: "read_at", bucket: "hour", sensorType: "temp" } },
  { id: "ov.sensor.phTrend", tab: "overview", label: "pH Trend", category: "Sensors / environment", description: "pH readings over time.", unit: "count", window: "range", render: "line", dataKey: "ov.sensor.phTrend", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "sensor_readings", measure: "value", dateCol: "read_at", bucket: "hour", sensorType: "ph" } },
  { id: "ov.sensor.humidityTrend", tab: "overview", label: "Humidity Trend", category: "Sensors / environment", description: "Humidity readings over time.", unit: "%", window: "range", render: "line", dataKey: "ov.sensor.humidityTrend", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "sensor_readings", measure: "value", dateCol: "read_at", bucket: "hour", sensorType: "humidity" } },
  { id: "ov.sensor.waterTrend", tab: "overview", label: "Water Level Trend", category: "Sensors / environment", description: "Water level readings over time.", unit: "%", window: "range", render: "area", dataKey: "ov.sensor.waterTrend", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "sensor_readings", measure: "value", dateCol: "read_at", bucket: "hour", sensorType: "water" } },
  { id: "ov.sensor.ecTrend", tab: "overview", label: "EC Trend", category: "Sensors / environment", description: "EC readings over time.", unit: "count", window: "range", render: "line", dataKey: "ov.sensor.ecTrend", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "sensor_readings", measure: "value", dateCol: "read_at", bucket: "hour", sensorType: "ec" } },
  { id: "ov.sensor.setpointVsActual", tab: "overview", label: "Setpoint vs Actual", category: "Sensors / environment", description: "growth_profiles setpoints vs sensor_readings (temp/pH).", unit: "count", window: "range", render: "line", dataKey: "ov.sensor.setpointVsActual", source: "metrics", defaultSelected: false },
  { id: "ov.sensor.outOfRange", tab: "overview", label: "Out-of-Range Events", category: "Sensors / environment", description: "Readings outside growth_profile ph/temp bounds.", unit: "count", window: "range", render: "kpi", dataKey: "ov.sensor.outOfRange", source: "metrics", defaultSelected: false },
  { id: "ov.sensor.uptime", tab: "overview", label: "Sensor Uptime", category: "Sensors / environment", description: "Sensors with last_read_at within freshness window.", unit: "%", window: "all", render: "kpi", dataKey: "ov.sensor.uptime", source: "metrics", defaultSelected: false },

  // ── Alerts ────────────────────────────────────────────────────────────
  { id: "ov.alerts.active", tab: "overview", label: "Alerts Requiring Action", category: "Alerts", description: "Active alerts (status=current).", unit: "count", window: "all", render: "kpi", dataKey: "alerts", source: "alerts", defaultSelected: true, panel: "alerts" },
  { id: "ov.alerts.critical", tab: "overview", label: "Critical Alerts", category: "Alerts", description: "Active alerts with severity=critical.", unit: "count", window: "all", render: "kpi", dataKey: "criticalAlertsCount", source: "dashboard", defaultSelected: false },
  { id: "ov.alerts.bySeverity", tab: "overview", label: "Alerts by Severity", category: "Alerts", description: "Active alerts grouped by severity.", unit: "count", window: "all", render: "donut", dataKey: "ov.alerts.bySeverity", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "alerts", measure: "*", dim: "severity", where: "status='current'" } },
  { id: "ov.alerts.byStatus", tab: "overview", label: "Alerts by Status", category: "Alerts", description: "Alerts grouped by status.", unit: "count", window: "all", render: "bar", dataKey: "ov.alerts.byStatus", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "alerts", measure: "*", dim: "status" } },
  { id: "ov.alerts.overTime", tab: "overview", label: "Alerts over Time", category: "Alerts", description: "Alerts created per week.", unit: "count", window: "all", render: "line", dataKey: "ov.alerts.overTime", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "alerts", measure: "*", dateCol: "created_at", bucket: "week" } },
  { id: "ov.alerts.byLocation", tab: "overview", label: "Alerts by Location", category: "Alerts", description: "Active alerts grouped by location.", unit: "count", window: "all", render: "bar", dataKey: "ov.alerts.byLocation", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "alerts", measure: "*", dim: "location", where: "status='current'" } },
  { id: "ov.alerts.mttr", tab: "overview", label: "Mean Time to Resolve", category: "Alerts", description: "AVG(resolved_at - created_at) for resolved alerts.", unit: "days", window: "all", render: "kpi", dataKey: "ov.alerts.mttr", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "alerts", measure: "extract(epoch from (resolved_at - created_at))/86400", agg: "avg", where: "status='resolved'" } },
  { id: "ov.alerts.resolved7d", tab: "overview", label: "Resolved (7d)", category: "Alerts", description: "Alerts resolved in last 7 days.", unit: "count", window: "7d", render: "kpi", dataKey: "ov.alerts.resolved7d", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "alerts", measure: "*", where: "status='resolved' AND resolved_at >= :weekStart" } },

  // ── Tasks ─────────────────────────────────────────────────────────────
  { id: "ov.tasks.open", tab: "overview", label: "Open Tasks", category: "Tasks", description: "Tasks not done.", unit: "count", window: "all", render: "kpi", dataKey: "ov.tasks.open", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "tasks", measure: "*", where: "status<>'done'" } },
  { id: "ov.tasks.byStatus", tab: "overview", label: "Tasks by Status", category: "Tasks", description: "Tasks grouped by status.", unit: "count", window: "all", render: "donut", dataKey: "ov.tasks.byStatus", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "tasks", measure: "*", dim: "status" } },
  { id: "ov.tasks.byType", tab: "overview", label: "Tasks by Type", category: "Tasks", description: "Tasks grouped by type.", unit: "count", window: "all", render: "bar", dataKey: "ov.tasks.byType", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "tasks", measure: "*", dim: "type" } },
  { id: "ov.tasks.overdue", tab: "overview", label: "Overdue Tasks", category: "Tasks", description: "Tasks with due_at < now and status<>done.", unit: "count", window: "all", render: "kpi", dataKey: "ov.tasks.overdue", source: "metrics", defaultSelected: false, template: "scalarAgg", templateParams: { table: "tasks", measure: "*", where: "due_at < now() AND status<>'done'" } },
  { id: "ov.tasks.completionRate", tab: "overview", label: "Task Completion Rate", category: "Tasks", description: "done / total tasks (rule 6).", unit: "%", window: "all", render: "kpi", dataKey: "ov.tasks.completionRate", source: "metrics", defaultSelected: false, template: "ratio", templateParams: { numTable: "tasks", numMeasure: "*", numWhere: "status='done'", denTable: "tasks", denMeasure: "*" } },
  { id: "ov.tasks.byAssignee", tab: "overview", label: "Tasks by Assignee", category: "Tasks", description: "Tasks grouped by assignee.", unit: "count", window: "all", render: "bar", dataKey: "ov.tasks.byAssignee", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "tasks", measure: "*", dim: "assignee" } },
  { id: "ov.tasks.throughput", tab: "overview", label: "Tasks Completed / Week", category: "Tasks", description: "Completed tasks per week.", unit: "count", window: "all", render: "line", dataKey: "ov.tasks.throughput", source: "metrics", defaultSelected: false, template: "timeBucket", templateParams: { table: "tasks", measure: "*", dateCol: "completed_at", bucket: "week", where: "status='done'" } },

  // ── Seed lots / crops ─────────────────────────────────────────────────
  { id: "ov.seedlots.active", tab: "overview", label: "Active Seed Lots", category: "Seed lots / crops", description: "Seed lots currently in rotation.", unit: "count", window: "all", render: "kpi", dataKey: "activeSeedLots", source: "dashboard", defaultSelected: true, panel: "seed-lots" },
  { id: "ov.seedlots.successRate", tab: "overview", label: "Lot Success %", category: "Seed lots / crops", description: "AVG seed_lots.success per lot.", unit: "%", window: "all", render: "bar", dataKey: "ov.seedlots.successRate", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "seed_lots", measure: "success", agg: "avg", dim: "id" } },
  { id: "ov.seedlots.growTime", tab: "overview", label: "Lot Grow Time", category: "Seed lots / crops", description: "AVG seed_lots.grow_time per lot.", unit: "days", window: "all", render: "bar", dataKey: "ov.seedlots.growTime", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "seed_lots", measure: "grow_time", agg: "avg", dim: "id" } },
  { id: "ov.seedlots.usage", tab: "overview", label: "Lot Usage Count", category: "Seed lots / crops", description: "Cycles per lot via cycle_seed_lots.", unit: "count", window: "all", render: "bar", dataKey: "ov.seedlots.usage", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycle_seed_lots", measure: "*", dim: "seed_lot_id" } },
  { id: "ov.crops.activeTypes", tab: "overview", label: "Active Crop Types", category: "Seed lots / crops", description: "Distinct crop_id in running cycles (rule 7).", unit: "count", window: "all", render: "kpi", dataKey: "activeCropTypes", source: "dashboard", defaultSelected: false },
  { id: "ov.crops.byCategory", tab: "overview", label: "Crops by Category", category: "Seed lots / crops", description: "Crops grouped by category enum.", unit: "count", window: "all", render: "donut", dataKey: "ov.crops.byCategory", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "crops", measure: "*", dim: "category" } },
  { id: "ov.crops.yieldCompare", tab: "overview", label: "Yield by Crop", category: "Seed lots / crops", description: "Harvested_qty per crop.", unit: "kg", window: "all", render: "bar", dataKey: "ov.crops.yieldCompare", source: "metrics", defaultSelected: false, template: "groupBy", templateParams: { table: "cycles", measure: "harvested_qty", dim: "crop_id" } },

  // ── Composite shims (M1 transition — decompose in M3) ─────────────────
  { id: "ov.combined.dailyYieldSeeding", tab: "overview", label: "Daily Yield vs Seeding", category: "Charts", description: "Combined daily yield (kg) and seeding weight (g), last 7 days. Composite shim — splits into per-metric Tier-B cards in M3.", unit: "", window: "7d", render: "bar", dataKey: "combinedDayData", source: "dashboard", defaultSelected: true },
  { id: "ov.combined.trend7d", tab: "overview", label: "7-Day Trend: Yield · Seeding · Bad Trays", category: "Charts", description: "Combined 7-day area: yield, seeding, bad trays. Composite shim — splits in M3.", unit: "", window: "7d", render: "area", dataKey: "combinedDayData", source: "dashboard", defaultSelected: true, span: 4 },
  { id: "ov.cycles.actionRequiredList", tab: "overview", label: "Action Required", category: "Cycles / activity", description: "List of cycles with overdue transitions (seedName, shortId, type, daysOverdue).", unit: "", window: "all", render: "list", dataKey: "actionRequired", source: "dashboard", defaultSelected: true, span: 2 },
];
